- name: "Check if Docker is installed"
  package_facts:
    manager: "auto"

- name: gather os specific variables
  include_tasks: "{{ item }}" 
  with_first_found:
    - "docker-task-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "docker-task-{{ ansible_distribution }}.yml"
  when: "'docker-ce' not in ansible_facts.packages"