- name: check LAMP stack
  shell: |
    [ -f compose.yaml ] && docker compose ls | grep -q '^lamp '
  args:
    chdir: /opt/LAMP
  ignore_errors: yes
  register: lamp_exists

- name: extract LAMP stack
  ansible.builtin.unarchive:
    src: LAMP.tgz
    dest: /opt
  when: "lamp_exists.rc != 0"

- name: run LAMP stack
  shell: |
    docker compose up -d
  args:
    chdir: /opt/LAMP
  environment: 
    MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    MYSQL_PASSWORD: "{{ mysql_password }}"
  register: dockercmd
  when: "lamp_exists.rc != 0"
