- name: "collect packages facts"
  package_facts:
    manager: "auto"

- name: run LAMP tasks
  include_tasks: "{{ item }}" 
  with_first_found:
    - "lamp-task-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "lamp-task-{{ ansible_distribution }}.yml"
  when: "'docker-ce' in ansible_facts.packages"

