version: '3'
services: 
  centos-nginx:
    image: "${IMG}"
    hostname: centos
    ports:
      - "8080-8084:80"
    networks:
      - backend
    environment:
      - "DEVOPS=${DEVOPS}"
      - "SERVER_NAME=${SERVER_NAME}"
    scale: 5
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - centos-nginx
    ports:
      - "80:4000"
    networks:
      - frontend
      - backend
networks:
  backend:
    driver: bridge
    name: backend
  frontend:
    driver: bridge
    name: frontend